FROM python:3.12-slim

WORKDIR /app

COPY requirements/requirements-fastapi.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY src/ ./src/
COPY api/ ./api/
COPY params.yaml .

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
