FROM python:3.12-slim

COPY requirements/requirements-mlflow.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

CMD mlflow server \
    --backend-store-uri ${MLFLOW_BACKEND_STORE_URI} \
    --artifacts-destination ${MLFLOW_ARTIFACTS_DESTINATION} \
    --serve-artifacts \
    --host 0.0.0.0 \
    --port 5000 \
    --workers 2 \
    --allowed-hosts '*'